version: 0.0.0

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bitcoin_agent
      POSTGRES_USER: bitcoin_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitcoin_user -d bitcoin_agent"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: